KEYWORDS = ['opium', 
            'poppy', 
            'anodyne', 
            'laudanum', 
            'morphine', 
            #'morphia', # ancestor of morphine that we discovered around the end of the analysis but could be interesting to add !
            'codein', 
            'heroin', 
            'narcotic', 
            'soporific', 
            'paregoric', 
            'dover\u2019s powder', 
            'chandu', 
            'nepenthe', 
            'dream-gum', 
            'dream-stick', 
            'black smoke']